# Generated by Django 6.0.4 on 2026-05-19 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evaluation_log_alter_weeklylog_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipplacement',
            name='Academic_supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'Acad_supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_supervisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
